=== Alyakhova/JD2018-11-13/src/by/it/nickgrudnitsky/jd02_07/person.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://it-academy.by.jd2018-11-13/nickgrudnitsky"
        xmlns:myType="http://it-academy.by.jd2018-11-13/nickgrudnitsky"
        elementFormDefault="qualified">

    <element name="persons">
        <complexType>
            <sequence>
                <element name="person"
                         type="myType:Person"
                         maxOccurs="unbounded">

                </element>
            </sequence>
        </complexType>
    </element>

    <complexType name="Person">
        <sequence>
            <element name="email" type="string"/>
            <element name="nickname" type="string"/>
            <element name="password" type="string"/>
            <element name="ads" type="myType:Ads"/>
        </sequence>

    </complexType>

    <complexType name="Ads">
        <sequence>
            <element name="ad"
                     type="myType:Ad"
                     minOccurs="0"
                     maxOccurs="unbounded"/>
        </sequence>

    </complexType>

    <complexType name="Ad">
        <all>
            <element name="description" type="string"/>
            <element name="adress" type="string"/>
            <element name="room" type="positiveInteger"/>
            <element name="floor" type="integer"/>
            <element name="floors" type="positiveInteger"/>
            <element name="area" type="float"/>
            <element name="price" type="string"/>
        </all>
    </complexType>

</schema>

=== Alyakhova/JD2018-11-13/src/by/it/nickgrudnitsky/jd02_07/person+xsd.xml
<?xml version="1.0" encoding="UTF-8"?>

<persons xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://it-academy.by.jd2018-11-13/nickgrudnitsky"
         xsi:schemaLocation="http://it-academy.by.jd2018-11-13/nickgrudnitsky person.xsd">


    <person>
        <email>vasya@gmail.com</email>
        <nickname>Vasya</nickname>
        <password>Vasya0000</password>
        <ads>
            <ad>
                <description>Flat</description>
                <adress>Minsk Gorodetskaya 44 126</adress>
                <room>3</room>
                <floor>3</floor>
                <floors>3</floors>
                <area>55.5</area>
                <price>100000</price>
            </ad>

            <ad>
                <description>Flat</description>
                <adress>Minsk Gorodetskaya 44 125</adress>
                <room>3</room>
                <floor>3</floor>
                <floors>3</floors>
                <area>40.5</area>
                <price>90000</price>
            </ad>

        </ads>

    </person>

</persons>
